name: CI_mypy

on: [pull_request, push]

jobs:
  run_mypy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install mypy
      run: sudo apt-get install -y mypy python3-mypy
    - name: Create default local config
      run: cp chc/util/ConfigLocal.template chc/util/ConfigLocal.py
    - name: Run mypy
      run: |
        PYTHONPATH=$PWD mypy chc
